let express = require('express')
let router = express.Router()
let member = require('./API/member')
let videotable = require('./API/video_table')
let booktable = require('./API/book_table')
let eventtable = require('./API/event_table')
let salestable = require('./API/sales_table')
let totaltable = require('./API/total_table')
let logintable = require('./API/login_page')
let registertable = require('./API/register_table')


router.get('/member', member.get)
router.get('/videotable', videotable.get)
router.get('/booktable', booktable.get)
router.get('/eventtable', eventtable.get)
router.get('/salestable', salestable.get)
router.get('/totaltable', totaltable.get)
router.get('/logintable', logintable.get)
router.post('/registertable', registertable.post)
router.get('/random_all', random_all.get) 
router.get('/random_appreciation', random_appreciation.get) 
router.get('/random_painting', random_painting.get) 
router.get('/random_art', random_art.get) 
router.get('/random_photography', random_photography.get) 

module.exports = router